#!/usr/bin/env bash

# a script used on CI to create a minified & un-minified browser bundle

mkdir -p build

cat <<JAVASCRIPT > build/index.js
import BugsnagPerformance from '@bugsnag/browser-performance'

BugsnagPerformance.start('abcdefabcdefabcdefabcdefabcdef12')
JAVASCRIPT

npm install @rollup/plugin-node-resolve @rollup/plugin-commonjs @rollup/plugin-terser

npx rollup build/index.js \
  --file build/bundle.js \
  --format iife \
  --plugin @rollup/plugin-commonjs \
  --plugin '@rollup/plugin-node-resolve={ browser: true }'

npx rollup build/index.js \
  --file build/bundle.min.js \
  --format iife \
  --plugin @rollup/plugin-commonjs \
  --plugin '@rollup/plugin-node-resolve={ browser: true }' \
  --plugin @rollup/plugin-terser
