source 'https://rubygems.org'

# You can run against local Maze Runner branches and uncommitted changes:
# gem 'bugsnag-maze-runner', path: '../../../maze-runner'

# Or a specific release:
gem 'bugsnag-maze-runner', '8.7.0'

# Or a branch
# gem 'bugsnag-maze-runner', git: 'https://github.com/bugsnag/maze-runner', branch: 'integration/v8'
