agents:
  queue: "opensource"

steps:
  - group: "Browser Tests"
    steps:

      - label: "Build browser fixtures${EXTRA_STEP_LABEL}"
        key: "build-browser-fixtures-${USE_CDN_BUILD}"
        timeout_in_minutes: 20
        agents:
          queue: macos-14
        env:
          USE_CDN_BUILD: "${USE_CDN_BUILD}"
          SKIP_FIXTURE_CLEANUP: "true"
        plugins:
          artifacts#v1.9.4:
            upload:
              - fixture-packages-${USE_CDN_BUILD}.zip
        commands:
          - cd ./test/browser
          - npm ci
          - ruby ./features/support/build-packages.rb
          - cd ../..
          - zip -r fixture-packages-${USE_CDN_BUILD}.zip test/browser/features/fixtures/packages
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

#      - label: ":docker: Build BitBar Maze Runner image${EXTRA_STEP_LABEL}"
#        key: "browser-maze-runner-bb-${USE_CDN_BUILD}"
#        timeout_in_minutes: 20
#        plugins:
#          - docker-compose#v4.12.0:
#              build: browser-maze-runner-bb
#              image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
#              cache-from: browser-maze-runner-bb:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}-${USE_CDN_BUILD}
#          - docker-compose#v4.12.0:
#              push: browser-maze-runner-bb:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}-${USE_CDN_BUILD}
#        env:
#          USE_CDN_BUILD: "${USE_CDN_BUILD}"
#        retry:
#          automatic:
#            - exit_status: "*"
#              limit: 1
#
#      - label: ":docker: Build BrowserStack Maze Runner image${EXTRA_STEP_LABEL}"
#        key: "browser-maze-runner-bs-${USE_CDN_BUILD}"
#        timeout_in_minutes: 20
#        plugins:
#          - docker-compose#v4.12.0:
#              build: browser-maze-runner-bs
#              image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
#              cache-from: browser-maze-runner-bs:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}-${USE_CDN_BUILD}
#          - docker-compose#v4.12.0:
#              push: browser-maze-runner-bs:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}-${USE_CDN_BUILD}
#        env:
#          USE_CDN_BUILD: "${USE_CDN_BUILD}"
#        retry:
#          automatic:
#            - exit_status: "*"
#              limit: 1
#
#      # BitBar
#      - label: ":bitbar: :{{ matrix.browser }}: {{ matrix.version }} tests${EXTRA_STEP_LABEL}"
#        depends_on: "browser-maze-runner-bb-${USE_CDN_BUILD}"
#        timeout_in_minutes: 30
#        plugins:
#          docker-compose#v4.12.0:
#            pull: browser-maze-runner-bb
#            run: browser-maze-runner-bb
#            use-aliases: true
#            service-ports: true
#            command:
#              - --https
#              - --farm=bb
#              - --browser={{ matrix.browser }}_{{ matrix.version }}
#              - --appium-version=1.22
#              - --aws-public-ip
#              - --no-tunnel
#          artifacts#v1.5.0:
#            upload:
#              - "./test/browser/maze_output/failed/**/*"
#          test-collector#v1.10.2:
#            files: "reports/TEST-*.xml"
#            format: "junit"
#            branch: "^main|next$$"
#            api-token-env-name: "BROWSER_PERFORMANCE_BUILDKITE_ANALYTICS_TOKEN"
#        concurrency: 25
#        concurrency_group: "bitbar"
#        matrix:
#          setup:
#            browser: [chrome, firefox]
#            version: [latest]
#          adjustments:
#            - with: { browser: safari, version: 18 }
#
#      # BrowserStack
#      - label: ":browserstack: :{{ matrix.browser }}: {{ matrix.version }} Browser tests${EXTRA_STEP_LABEL}"
#        depends_on: "browser-maze-runner-bs-${USE_CDN_BUILD}"
#        timeout_in_minutes: 30
#        plugins:
#          docker-compose#v4.12.0:
#            pull: browser-maze-runner-bs
#            run: browser-maze-runner-bs
#            use-aliases: true
#            command:
#              - --https
#              - --farm=bs
#              - --browser={{ matrix.browser }}_{{ matrix.version }}
#          artifacts#v1.5.0:
#            upload:
#              - "./test/browser/maze_output/failed/**/*"
#          test-collector#v1.10.2:
#            files: "reports/TEST-*.xml"
#            format: "junit"
#            branch: "^main|next$$"
#            api-token-env-name: "BROWSER_PERFORMANCE_BUILDKITE_ANALYTICS_TOKEN"
#        concurrency: 2
#        concurrency_group: "browserstack"
#        matrix:
#          setup:
#            browser: [chrome]
#            version: [61]
#          adjustments:
#            - with: { browser: firefox, version: 60 }
#            - with: { browser: edge, version: 80 }
#            - with: { browser: edge, version: latest }
#
#      # BrowserStack non-https
#      - label: ":browserstack: :{{ matrix.browser }}: {{ matrix.version }} Browser non-https tests${EXTRA_STEP_LABEL}"
#        depends_on: "browser-maze-runner-bs-${USE_CDN_BUILD}"
#        timeout_in_minutes: 30
#        plugins:
#          docker-compose#v4.12.0:
#            pull: browser-maze-runner-bs
#            run: browser-maze-runner-bs
#            use-aliases: true
#            command:
#              - --farm=bs
#              - --browser={{ matrix.browser }}_{{ matrix.version }}
#          artifacts#v1.5.0:
#            upload:
#              - "./test/browser/maze_output/failed/**/*"
#          test-collector#v1.10.2:
#            files: "reports/TEST-*.xml"
#            format: "junit"
#            branch: "^main|next$$"
#            api-token-env-name: "BROWSER_PERFORMANCE_BUILDKITE_ANALYTICS_TOKEN"
#        concurrency: 2
#        concurrency_group: "browserstack"
#        matrix:
#          setup:
#            browser: [safari]
#            version: [11]
