steps:

  - label: ":browserstack: {{ matrix }} Mobile Browser tests"
    matrix:
      - android_13
      - ios_12
      - ios_16
    depends_on: "browser-maze-runner-bs"
    timeout_in_minutes: 30
    plugins:
      docker-compose#v4.12.0:
        pull: browser-maze-runner-bs
        run: browser-maze-runner-bs
        use-aliases: true
        command:
          - --farm=bs
          - --browser={{ matrix }}
      artifacts#v1.5.0:
        upload:
          - "./test/browser/maze_output/failed/**/*"
    concurrency: 2
    concurrency_group: "browserstack"
