agents:
  queue: "opensource"

steps:
  - group: "Browser Tests"
    steps:
      - label: ":browserstack: {{ matrix }} Mobile Browser tests"
        matrix:
          - android_13
          - ios_13
          - ios_18
        depends_on: "build-browser-fixtures-NPM"
        timeout_in_minutes: 30
        plugins:
          docker-compose#v4.12.0:
            pull: browser-maze-runner-bs
            run: browser-maze-runner-bs
            use-aliases: true
            command:
              - --farm=bs
              - --browser={{ matrix }}
          artifacts#v1.9.4:
            download:
              - "fixture-packages-NPM.zip"
              - from: "test/browser/features/fixtures/.bugsnag-browser-version-NPM"
                to: "test/browser/features/fixtures/.bugsnag-browser-version"
            upload:
              - "./test/browser/maze_output/failed/**/*"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "BROWSER_PERFORMANCE_BUILDKITE_ANALYTICS_TOKEN"
        concurrency: 2
        concurrency_group: "browserstack"
        concurrency_method: eager

      - label: ":pipeline_upload: Basic browser pipeline with CDN build"
        agents:
          queue: "macos"
        timeout_in_minutes: 2
        commands:
          - BUILD_MODE=CDN buildkite-agent pipeline upload .buildkite/browser-pipeline.yml
