steps:

  - group: "Browser Tests"
    steps:
      - label: ":docker: Build browser maze runner image"
        key: "browser-maze-runner"
        timeout_in_minutes: 20
        plugins:
          - docker-compose#v3.9.0:
              build: browser-maze-runner
              image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
              cache-from: browser-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}
          - docker-compose#v3.9.0:
              push: browser-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}

      - label:  ":docker: Build legacy browser maze runner image"
        key: "browser-maze-runner-legacy"
        timeout_in_minutes: 20
        plugins:
          - docker-compose#v3.9.0:
              build: browser-maze-runner-legacy
              image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
              cache-from: browser-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-legacy-${BRANCH_NAME}
          - docker-compose#v3.9.0:
              push: browser-maze-runner:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-legacy-${BRANCH_NAME}

      # BitBar
      - label: ":{{ matrix.browser }}: {{ matrix.version }} tests"
        depends_on: "browser-maze-runner"
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.9.0:
            pull: browser-maze-runner
            run: browser-maze-runner
            use-aliases: true
            command:
              - --farm=bb
              - --browser={{ matrix.browser }}_{{ matrix.version }}
          artifacts#v1.5.0:
            upload:
              - "./test/browser/maze_output/failed/**/*"
        concurrency: 5
        concurrency_group: "bitbar-web"
        matrix:
          setup:
            browser: [chrome, firefox, edge]
            version: [latest]
          adjustments:
            - with: { browser: safari, version: 16 }

      # BrowserStack
      - label: ":{{ matrix.browser }}: {{ matrix.version }} Browser tests"
        depends_on: "browser-maze-runner-legacy"
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.9.0:
            pull: browser-maze-runner-legacy
            run: browser-maze-runner-legacy
            use-aliases: true
            command:
              - --farm=bs
              - --browser={{ matrix.browser }}_{{ matrix.version }}
          artifacts#v1.5.0:
            upload:
              - "./test/browser/maze_output/failed/**/*"
        concurrency: 2
        concurrency_group: "browserstack"
        matrix:
          setup:
            browser: [chrome]
            version: [61]
          adjustments:
            - with: { browser: firefox, version: 60 }
            - with: { browser: edge, version: 80 }
            - with: { browser: safari, version: 11 }

      # BrowserStack - iOS
      - label: ":ios: iOS {{ matrix.os }} Browser tests"
        depends_on: "browser-maze-runner"
        timeout_in_minutes: 30
        env:
          HOST: "bs-local.com"
        plugins:
          docker-compose#v3.9.0:
            pull: browser-maze-runner
            run: browser-maze-runner
            use-aliases: true
            command:
              - --farm=bs
              - --browser={{ matrix.device }}
          artifacts#v1.5.0:
            upload:
              - "./test/browser/maze_output/failed/**/*"
        concurrency: 2
        concurrency_group: "browserstack"
        matrix:
          setup:
            device: [iphone_x]
            os: [11]
          adjustments:
            - with: { device: iphone_13, os: 13 }

      # BrowserStack - Android
      - label: ":android: Android {{ matrix.os }} Browser tests"
        depends_on: "browser-maze-runner" # not legacy?
        timeout_in_minutes: 30
        plugins:
          docker-compose#v3.9.0:
            pull: browser-maze-runner
            run: browser-maze-runner
            use-aliases: true
            command:
              - --farm=bs
              - --browser={{ matrix.device }}
          artifacts#v1.5.0:
            upload:
              - "./test/browser/maze_output/failed/**/*"
        concurrency: 2
        concurrency_group: "browserstack"
        matrix:
          setup:
            device: [android_s6]
            os: [5]
          adjustments:
            - with: { device: android_s8, os: 7 }
