agents:
  queue: "opensource"

steps:
  - group: "Browser Tests"
    steps:

      - label: "Build browser fixtures - ${BUILD_MODE}"
        key: "build-browser-fixtures-${BUILD_MODE}"
        timeout_in_minutes: 20
        agents:
          queue: macos-14
        env:
          BUILD_MODE: "${BUILD_MODE}"
          SKIP_FIXTURE_CLEANUP: "true"
        plugins:
          artifacts#v1.9.4:
            upload:
              - "fixture-packages-${BUILD_MODE}.zip"
              - from: "test/browser/features/fixtures/.bugsnag-browser-version"
                to: "test/browser/features/fixtures/.bugsnag-browser-version-${BUILD_MODE}"
        commands:
          - cd ./test/browser
          - npm ci
          - ruby ./features/support/build-packages.rb
          - cd ../..
          - zip -r fixture-packages-${BUILD_MODE}.zip test/browser/features/fixtures/packages
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      # BitBar
      - label: ":bitbar: :{{ matrix.browser }}: {{ matrix.version }} tests - ${BUILD_MODE}"
        depends_on: "build-browser-fixtures-${BUILD_MODE}"
        timeout_in_minutes: 30
        plugins:
          artifacts#v1.9.4:
            download:
              - "fixture-packages-${BUILD_MODE}.zip"
              - from: "test/browser/features/fixtures/.bugsnag-browser-version-${BUILD_MODE}"
                to: "test/browser/features/fixtures/.bugsnag-browser-version"
            upload: "./test/browser/maze_output/failed/**/*"
          improbable-eng/metahook:
            pre-command: "unzip -o fixture-packages-${BUILD_MODE}.zip"
          docker-compose#v4.12.0:
            pull: browser-maze-runner-bb
            run: browser-maze-runner-bb
            use-aliases: true
            service-ports: true
            command:
              - --https
              - --farm=bb
              - --browser={{ matrix.browser }}_{{ matrix.version }}
              - --appium-version=1.22
              - --aws-public-ip
              - --no-tunnel
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "BROWSER_PERFORMANCE_BUILDKITE_ANALYTICS_TOKEN"
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          setup:
            browser: [chrome, firefox]
            version: [latest]
          adjustments:
            - with: { browser: safari, version: 18 }

      # BrowserStack
      - label: ":browserstack: :{{ matrix.browser }}: {{ matrix.version }} Browser tests - ${BUILD_MODE}"
        depends_on: "build-browser-fixtures-${BUILD_MODE}"
        timeout_in_minutes: 30
        plugins:
          artifacts#v1.9.4:
            download:
              - "fixture-packages-${BUILD_MODE}.zip"
              - from: "test/browser/features/fixtures/.bugsnag-browser-version-${BUILD_MODE}"
                to: "test/browser/features/fixtures/.bugsnag-browser-version"
            upload: "./test/browser/maze_output/failed/**/*"
          improbable-eng/metahook:
            pre-command: "unzip -o fixture-packages-${BUILD_MODE}.zip"
          docker-compose#v4.12.0:
            pull: browser-maze-runner-bs
            run: browser-maze-runner-bs
            use-aliases: true
            command:
              - --https
              - --farm=bs
              - --browser={{ matrix.browser }}_{{ matrix.version }}
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "BROWSER_PERFORMANCE_BUILDKITE_ANALYTICS_TOKEN"
        concurrency: 2
        concurrency_group: "browserstack"
        concurrency_method: eager
        matrix:
          setup:
            browser: [chrome]
            version: [61]
          adjustments:
            - with: { browser: firefox, version: 60 }
            - with: { browser: edge, version: 80 }
            - with: { browser: edge, version: latest }

      # BrowserStack non-https
      - label: ":browserstack: :{{ matrix.browser }}: {{ matrix.version }} Browser non-https tests - ${BUILD_MODE}"
        depends_on: "build-browser-fixtures-${BUILD_MODE}"
        timeout_in_minutes: 30
        plugins:
          artifacts#v1.9.4:
            download:
              - "fixture-packages-${BUILD_MODE}.zip"
              - from: "test/browser/features/fixtures/.bugsnag-browser-version-${BUILD_MODE}"
                to: "test/browser/features/fixtures/.bugsnag-browser-version"
            upload: "./test/browser/maze_output/failed/**/*"
          improbable-eng/metahook:
            pre-command: "unzip -o fixture-packages-${BUILD_MODE}.zip"
          docker-compose#v4.12.0:
            pull: browser-maze-runner-bs
            run: browser-maze-runner-bs
            use-aliases: true
            command:
              - --farm=bs
              - --browser={{ matrix.browser }}_{{ matrix.version }}
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "BROWSER_PERFORMANCE_BUILDKITE_ANALYTICS_TOKEN"
        concurrency: 2
        concurrency_group: "browserstack"
        concurrency_method: eager
        matrix:
          setup:
            browser: [safari]
            version: [11]
