agents:
  queue: "opensource"

steps:
  - group: "Browser Tests"
    steps:
      - label: ":docker: Build BrowserStack Maze Runner image${EXTRA_STEP_LABEL}"
        key: "browser-maze-runner-bs-${USE_CDN_BUILD}"
        timeout_in_minutes: 20
        plugins:
          - docker-compose#v4.12.0:
              build: browser-maze-runner-bs
              image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
              cache-from: browser-maze-runner-bs:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}-${USE_CDN_BUILD}
          - docker-compose#v4.12.0:
              push: browser-maze-runner-bs:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}-${USE_CDN_BUILD}
        env:
          USE_CDN_BUILD: "${USE_CDN_BUILD}"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      # BrowserStack
      - label: ":browserstack: :{{ matrix.browser }}: {{ matrix.version }} Browser tests${EXTRA_STEP_LABEL}"
        depends_on: "browser-maze-runner-bs-${USE_CDN_BUILD}"
        timeout_in_minutes: 30
        plugins:
          docker-compose#v4.12.0:
            pull: browser-maze-runner-bs
            run: browser-maze-runner-bs
            use-aliases: true
            command:
              - --https
              - --farm=bs
              - --browser={{ matrix.browser }}_{{ matrix.version }}
          artifacts#v1.5.0:
            upload:
              - "./test/browser/maze_output/failed/**/*"
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "BROWSER_PERFORMANCE_BUILDKITE_ANALYTICS_TOKEN"
        concurrency: 2
        concurrency_group: "browserstack"
        matrix:
          setup:
            browser: [edge]
            version: [80,81]
