steps:

  - group: "Browser Tests"
    steps:
      - label: ":docker: Build BitBar Maze Runner image"
        key: "browser-maze-runner-bb"
        timeout_in_minutes: 20
        plugins:
          - docker-compose#v4.12.0:
              build: browser-maze-runner-bb
              image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
              cache-from: browser-maze-runner-bb:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}
          - docker-compose#v4.12.0:
              push: browser-maze-runner-bb:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}

      - label: ":docker: Build BrowserStack Maze Runner image"
        key: "browser-maze-runner-bs"
        timeout_in_minutes: 20
        plugins:
          - docker-compose#v4.12.0:
              build: browser-maze-runner-bs
              image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
              cache-from: browser-maze-runner-bs:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}
          - docker-compose#v4.12.0:
              push: browser-maze-runner-bs:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}

      - label: ":docker: Build Legacy Maze Runner image"
        key: "browser-maze-runner-legacy"
        timeout_in_minutes: 20
        plugins:
          - docker-compose#v4.12.0:
              build: browser-maze-runner-legacy
              image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
              cache-from: browser-maze-runner-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}
          - docker-compose#v4.12.0:
              push: browser-maze-runner-legacy:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}

      # BitBar
      - label: ":bitbar: :{{ matrix.browser }}: {{ matrix.version }} tests"
        depends_on: "browser-maze-runner-bb"
        timeout_in_minutes: 30
        plugins:
          docker-compose#v4.12.0:
            pull: browser-maze-runner-bb
            run: browser-maze-runner-bb
            use-aliases: true
            service-ports: true
            command:
              - --farm=bb
              - --browser={{ matrix.browser }}_{{ matrix.version }}
              - --aws-public-ip
              - --no-tunnel
          artifacts#v1.5.0:
            upload:
              - "./test/browser/maze_output/failed/**/*"
        concurrency: 5
        concurrency_group: "bitbar-web"
        matrix:
          setup:
            browser: [chrome, firefox, edge]
            version: [latest]
          adjustments:
            - with: { browser: safari, version: 16 }

      # BrowserStack
      - label: ":browserstack: :{{ matrix.browser }}: {{ matrix.version }} Browser tests"
        depends_on: "browser-maze-runner-legacy"
        timeout_in_minutes: 30
        plugins:
          docker-compose#v4.12.0:
            pull: browser-maze-runner-legacy
            run: browser-maze-runner-legacy
            use-aliases: true
            command:
              - --farm=bs
              - --browser={{ matrix.browser }}_{{ matrix.version }}
          artifacts#v1.5.0:
            upload:
              - "./test/browser/maze_output/failed/**/*"
        concurrency: 2
        concurrency_group: "browserstack"
        matrix:
          setup:
            browser: [chrome]
            version: [61]
          adjustments:
            - with: { browser: firefox, version: 60 }
            - with: { browser: edge, version: 80 }
            - with: { browser: safari, version: 11 }
