steps:
  - label: ":docker: Build BrowserStack Maze Runner image"
    key: "browser-maze-runner-bs"
    timeout_in_minutes: 20
    plugins:
      - docker-compose#v4.12.0:
          build: browser-maze-runner-bs
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from: browser-maze-runner-bs:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}-${USE_CDN_BUILD}
      - docker-compose#v4.12.0:
          push: browser-maze-runner-bs:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:performance-ci-browser-${BRANCH_NAME}-${USE_CDN_BUILD}
    env:
      USE_CDN_BUILD: "${USE_CDN_BUILD}"

  - label: ":browserstack: {{ matrix }} Mobile Browser tests"
    matrix:
      - android_13
      - ios_12
      - ios_16
    depends_on: "browser-maze-runner-bs"
    timeout_in_minutes: 30
    plugins:
      docker-compose#v4.12.0:
        pull: browser-maze-runner-bs
        run: browser-maze-runner-bs
        use-aliases: true
        command:
          - --farm=bs
          - --browser={{ matrix }}
      artifacts#v1.5.0:
        upload:
          - "./test/browser/maze_output/failed/**/*"
    concurrency: 2
    concurrency_group: "browserstack"

  - label: ":pipeline_upload: Basic browser pipeline with CDN build"
    commands:
      - USE_CDN_BUILD=1 EXTRA_STEP_LABEL=" (CDN)" buildkite-agent pipeline upload .buildkite/browser-pipeline.yml
