steps:

  #
  # License audit
  #
  - label: ":copyright: License Audit"
    timeout_in_minutes: 20
    plugins:
      - docker-compose#v3.9.0:
          run: license-finder

  #
  # Upload browser-pipeline yaml 
  #
  - label: ":pipeline_upload:"
    commands:
      - buildkite-agent pipeline upload .buildkite/browser-pipeline.yml
