steps:

  #
  # License audit
  #
  - label: ":copyright: License Audit"
    timeout_in_minutes: 20
    plugins:
      - docker-compose#v4.12.0:
          run: license-finder

  #
  # Upload each basic pipeline
  #
  - label: ":pipeline_upload: Basic browser pipeline"
    commands:
      - buildkite-agent pipeline upload .buildkite/browser-pipeline.yml

  #
  # Conditionally trigger full pipeline
  #
  - label: 'Conditionally trigger full set of tests'
    timeout_in_minutes: 30
    command: sh -c .buildkite/pipeline_trigger.sh
