steps:

  #
  # License audit
  #
  - label: ":copyright: License Audit"
    timeout_in_minutes: 20
    agents:
      queue: macos-12-arm
    command: scripts/license_finder.sh

  #
  # Publish/package notifier
  #
  # - label: ":docker: Prepare package.json"
  #   key: "package-js"
  #   timeout_in_minutes: 3
  #   plugins:
  #     - docker-compose#v3.9.0:
  #         run: minimal-packager
  #   artifact_paths: min_packages.tar

  # - label: ":docker: Build and publish JS packages"
  #   key: "publish-js"
  #   timeout_in_minutes: 30
  #   plugins:
  #     - docker-compose#v3.9.0:
  #         build: publisher
  #         image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js

  #
  # Core tests and checks
  #
  # - label: ":docker: Build CI image"
  #   key: "ci-image"
  #   depends_on: "package-js"
  #   timeout_in_minutes: 20
  #   plugins:
  #     - artifacts#v1.5.0:
  #         download: min_packages.tar
  #     - docker-compose#v3.9.0:
  #         build:
  #           - ci
  #         image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
  #         cache-from:
  #           - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base-${BRANCH_NAME}
  #           - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base
  #     - docker-compose#v3.9.0:
  #         push:
  #           - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base-${BRANCH_NAME}
  #           - ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:ci-base

  # - label: "Lint"
  #   depends_on: "ci-image"
  #   timeout_in_minutes: 10
  #   plugins:
  #     docker-compose#v3.9.0:
  #       run: ci
  #   command: "npm run test:lint"

  # - label: "Unit tests"
  #   depends_on: "ci-image"
  #   timeout_in_minutes: 10
  #   plugins:
  #     docker-compose#v3.9.0:
  #       run: ci
  #   command: "npm run test:unit"

  # - label: "Type checks/tests"
  #   depends_on: "ci-image"
  #   timeout_in_minutes: 10
  #   plugins:
  #     docker-compose#v3.9.0:
  #       run: ci
  #   command: "npm run test:types"

  # - label: ":large_blue_circle: :large_blue_circle: :large_blue_circle: BROWSER STEPS :large_blue_circle: :large_blue_circle: :large_blue_circle:"
  #   depends_on: "package-js"
  #   commands:
  #     - buildkite-agent pipeline upload .buildkite/browser-pipeline.yml
