agents:
  queue: macos

steps:

  #
  # License audit
  #
  - label: ":copyright: License Audit"
    agents:
      queue: opensource
    timeout_in_minutes: 20
    plugins:
      - docker-compose#v4.12.0:
          run: license-finder

  #
  # Detect changes and upload relevant pipelines
  #
  - label: ":git: Detect changed packages"
    agents:
      queue: "macos-node-18"
    timeout_in_minutes: 5
    command: node .buildkite/scripts/pipeline-trigger.js

  - label: ":pipeline_upload: Basic browser pipeline with NPM build"
    agents:
      queue: "macos"
    timeout_in_minutes: 2
    commands:
      - USE_CDN_BUILD=0 EXTRA_STEP_LABEL=" (NPM)" buildkite-agent pipeline upload .buildkite/browser-pipeline.yml

  - label: ":pipeline_upload: Basic browser pipeline with CDN build"
    agents:
      queue: "macos"
    timeout_in_minutes: 2
    commands:
      - USE_CDN_BUILD=1 EXTRA_STEP_LABEL=" (CDN)" buildkite-agent pipeline upload .buildkite/browser-pipeline.yml
