steps:

  - label: ':android: Build RN {{matrix}} test fixture APK'
    key: "build-react-native-android-fixture"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    env:
      RN_VERSION: "{{matrix}}"
      BUILD_ANDROID: "true"
    artifact_paths:
      - "build/react-native/**/reactnative.apk"
    commands:
      - ./bin/generate-react-native-fixture
    matrix:
      - "0.71"
      - "0.72"

  - label: ':mac: Build RN {{matrix}} test fixture ipa'
    key: "build-react-native-ios-fixture"
    timeout_in_minutes: 30
    agents:
      queue: "macos-12-arm"
    env:
      RN_VERSION: "{{matrix}}"
      BUILD_IOS: "true"
      DEVELOPER_DIR: "/Applications/Xcode14.app"
    artifact_paths:
      - "build/react-native/**/output/reactnative.ipa"
    commands:
      - ./bin/generate-react-native-fixture
    matrix:
      - "0.71"
      - "0.72"