steps:
  - group: "React Native Tests"
    steps:
      #
      # Test fixtures
      #
      - label: ':android: Build RN {{matrix.reactnative}} test fixture APK (Old Arch)'
        key: "build-react-native-android-fixture-old-arch-full"
        timeout_in_minutes: 30
        agents:
          queue: macos-14
        env:
          JAVA_VERSION: "{{matrix.java}}"
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix.reactnative}}"
          NOTIFIER_VERSION: '8.0.0-alpha.13'
          BUILD_ANDROID: "true"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/old-arch/**/reactnative.apk"
        commands:
          - ./bin/generate-react-native-fixture
        matrix:
          setup:
            reactnative:
              - "0.71"
              - "0.72"
              - "0.73"
            java:
              - "17"
          adjustments:
            - with:
                reactnative: "0.64"
                java: "11"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ':android: Build RN {{matrix}} test fixture APK (New Arch)'
        key: "build-react-native-android-fixture-new-arch-full"
        timeout_in_minutes: 30
        agents:
          queue: macos-14
        env:
          JAVA_VERSION: "17"
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          NOTIFIER_VERSION: '8.0.0-alpha.13'
          RCT_NEW_ARCH_ENABLED: "true"
          BUILD_ANDROID: "true"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/new-arch/**/reactnative.apk"
        commands:
          - ./bin/generate-react-native-fixture
        matrix:
          - "0.71"
          - "0.72"
          - "0.73"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ':mac: Build RN {{matrix}} test fixture ipa (Old Arch)'
        key: "build-react-native-ios-fixture-old-arch-full"
        timeout_in_minutes: 30
        agents:
          queue: "macos-14"
        env:
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          NOTIFIER_VERSION: '8.0.0-alpha.13'
          BUILD_IOS: "true"
          XCODE_VERSION: "15.3.0"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/old-arch/**/output/reactnative.ipa"
        commands:
          - bundle install
          - ./bin/generate-react-native-fixture
        matrix:
          - "0.64"
          - "0.71"
          - "0.72"
          - "0.73"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ':mac: Build RN {{matrix}} test fixture ipa (New Arch)'
        key: "build-react-native-ios-fixture-new-arch-full"
        timeout_in_minutes: 30
        agents:
          queue: "macos-14"
        env:
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          NOTIFIER_VERSION: '8.0.0-alpha.13'
          RCT_NEW_ARCH_ENABLED: "1"
          BUILD_IOS: "true"
          XCODE_VERSION: "15.3.0"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/new-arch/**/output/reactnative.ipa"
        commands:
          - bundle install
          - ./bin/generate-react-native-fixture
        matrix:
          - "0.71"
          - "0.72"
          - "0.73"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

        #
        # End-to-end tests
        #
      - label: ":bitbar: :android: RN {{matrix}} Android 12 (Old Arch) end-to-end tests"
        depends_on: "build-react-native-android-fixture-old-arch-full"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/old-arch/{{matrix}}/reactnative.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/old-arch/{{matrix}}/reactnative.apk
              - --farm=bb
              - --device=ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --appium-version=1.22
              - --no-tunnel
              - --aws-public-ip
        retry:
          manual:
            permit_on_passed: true
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.64"
          - "0.71"
          - "0.72"
          - "0.73"

      - label: ":bitbar: :android: RN {{matrix}} Android 12 (New Arch) end-to-end tests"
        depends_on: "build-react-native-android-fixture-new-arch-full"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/new-arch/{{matrix}}/reactnative.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/new-arch/{{matrix}}/reactnative.apk
              - --farm=bb
              - --device=ANDROID_12
              - --a11y-locator
              - --fail-fast
              - --appium-version=1.22
              - --no-tunnel
              - --aws-public-ip
        env:
          RCT_NEW_ARCH_ENABLED: "1"
        retry:
          manual:
            permit_on_passed: true
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.71"
          - "0.72"
          - "0.73"

      - label: ":bitbar: :mac: RN {{matrix}} iOS 14 (Old Arch) end-to-end tests"
        depends_on: "build-react-native-ios-fixture-old-arch-full"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/old-arch/{{matrix}}/output/reactnative.ipa"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/old-arch/{{matrix}}/output/reactnative.ipa
              - --farm=bb
              - --device=IOS_14
              - --a11y-locator
              - --fail-fast
              - --appium-version=1.22
              - --no-tunnel
              - --aws-public-ip
        retry:
          manual:
            permit_on_passed: true
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.64"
          - "0.71"
          - "0.72"
          - "0.73"

      - label: ":bitbar: :mac: RN {{matrix}} iOS 14 (New Arch) end-to-end tests"
        depends_on: "build-react-native-ios-fixture-new-arch-full"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/new-arch/{{matrix}}/output/reactnative.ipa"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/new-arch/{{matrix}}/output/reactnative.ipa
              - --farm=bb
              - --device=IOS_14
              - --a11y-locator
              - --fail-fast
              - --appium-version=1.22
              - --no-tunnel
              - --aws-public-ip
        env:
          RCT_NEW_ARCH_ENABLED: "1"
        retry:
          manual:
            permit_on_passed: true
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.71"
          - "0.72"
          - "0.73"
