steps:

  - label: ':android: Build RN test fixture APK'
    key: "build-react-native-android-fixture"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    env:
      RN_VERSION: "0.72"
      BUILD_ANDROID: "true"
    artifact_paths:
      - "build/react-native/0.72/reactnative.apk"
    commands:
      - ./bin/generate-react-native-fixture

  - label: ':mac: Build RN test fixture ipa'
    key: "build-react-native-ios-fixture"
    timeout_in_minutes: 30
    agents:
      queue: "opensource-arm-mac-cocoa-12"
    env:
      RN_VERSION: "0.72"
      BUILD_IOS: "true"
      DEVELOPER_DIR: "/Applications/Xcode14.app"
    artifact_paths:
      - "build/react-native/0.72/output/reactnative.ipa"
    commands:
      - ./bin/generate-react-native-fixture