agents:
  queue: "opensource"

steps:
  - group: "React Native Benchmark Tests"
    steps:
      #
      # Build fixtures
      #
      - label: ':android: Build RN {{matrix}} benchmark fixture APK (New Arch)'
        key: "build-react-native-android-fixture-benchmark-new-arch"
        timeout_in_minutes: 30
        agents:
          queue: macos-15
        env:
          JAVA_VERSION: "17"
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          NOTIFIER_VERSION: "8.0.0"
          RCT_NEW_ARCH_ENABLED: "1"
          BUILD_ANDROID: "true"
          NATIVE_INTEGRATION: "1"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/native-integration/new-arch/**/reactnative.apk"
        commands:
          - bundle install
          - node test/react-native/scripts/generate-react-native-fixture.js
        matrix:
          - "0.80"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1
        
      - label: ':mac: Build RN {{matrix}} benchmark fixture ipa (New Arch)'
        key: "build-react-native-ios-fixture-benchmark-new-arch"
        timeout_in_minutes: 30
        agents:
          queue: "macos-15"
        env:
          NODE_VERSION: "18"
          RN_VERSION: "{{matrix}}"
          RCT_NEW_ARCH_ENABLED: "1"
          NOTIFIER_VERSION: "8.0.0"
          BUILD_IOS: "true"
          XCODE_VERSION: "16.2.0"
          NATIVE_INTEGRATION: "1"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/native-integration/new-arch/**/output/reactnative.ipa"
        commands:
          - bundle install
          - node test/react-native/scripts/generate-react-native-fixture.js
        matrix:
          - "0.80"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      #
      # Run benchmarks
      #
      - label: ":bitbar: :android: RN {{matrix}} Android Benchmarks"
        depends_on: "build-react-native-android-fixture-benchmark-new-arch"
        timeout_in_minutes: 20
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/native-integration/new-arch/{{matrix}}/reactnative.apk"
            upload:
              - "./test/react-native/maze_output/failed/*"
              - "./test/react-native/maze_output/maze_output.zip"
              - "./test/react-native/maze_output/metrics.csv"
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/native-integration/new-arch/{{matrix}}/reactnative.apk
              - --farm=bb
              - --device=ANDROID_13
              - --a11y-locator
              - --fail-fast
              - --appium-version=1.22
              - --no-tunnel
              - --aws-public-ip
              - --tags=@benchmark
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_PERFORMANCE_BUILDKITE_ANALYTICS_TOKEN"
        env:
          RCT_NEW_ARCH_ENABLED: "1"
          NATIVE_INTEGRATION: "1"
          BENCHMARKS: "1"
          RN_VERSION: "{{matrix}}"
        retry:
          manual:
            permit_on_passed: true
          automatic:
            - exit_status: 103  # Appium session failed
              limit: 2
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.80"

      - label: ":bitbar: :mac: RN {{matrix}} iOS Benchmarks"
        depends_on: "build-react-native-ios-fixture-benchmark-new-arch"
        timeout_in_minutes: 20
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/native-integration/new-arch/{{matrix}}/output/reactnative.ipa"
            upload:
              - "./test/react-native/maze_output/failed/*"
              - "./test/react-native/maze_output/maze_output.zip"
              - "./test/react-native/maze_output/metrics.csv"
          docker-compose#v4.12.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - --app=/app/features/fixtures/generated/native-integration/new-arch/{{matrix}}/output/reactnative.ipa
              - --farm=bb
              - --device=IOS_14|IOS_15|IOS_16|IOS_17|IOS_18|IOS_26
              - --a11y-locator
              - --fail-fast
              - --appium-version=1.22
              - --no-tunnel
              - --aws-public-ip
              - --tags=@benchmark
          test-collector#v1.10.2:
            files: "reports/TEST-*.xml"
            format: "junit"
            branch: "^main|next$$"
            api-token-env-name: "REACT_NATIVE_PERFORMANCE_BUILDKITE_ANALYTICS_TOKEN"
        env:
          RCT_NEW_ARCH_ENABLED: "1"
          NATIVE_INTEGRATION: "1"
          BENCHMARKS: "1"
          RN_VERSION: "{{matrix}}"
        retry:
          manual:
            permit_on_passed: true
          automatic:
            - exit_status: 103  # Appium session failed
              limit: 2
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          - "0.80"
