steps:
  - group: "React native navigation android tests"
    steps:
      - label: ":android: Build react-native-navigation fixture - rn_{{matrix.rn_version}} - {{matrix.rn_arch}}"
        key: "build-react-native-navigation-android-fixture"
        timeout_in_minutes: 30
        agents:
          queue: macos-12-arm
        env:
          BUILD_ANDROID: "true"
          RCT_NEW_ARCH_ENABLED: "{{matrix.rn_arch == 'new-arch'}}"
          RN_VERSION: "{{matrix.rn_version}}"
        artifact_paths:
          - "test/react-native-navigation/features/fixtures/generated/react-native-navigation/**/reactnative.apk"
        commands:
          - ./bin/generate-react-native-navigation-fixture
        matrix:
          setup:
            rn_arch:
              - "new-arch"
              - "old-arch"
            rn_version:
              - "0.71"
              - "0.72"
              - "0.73"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1