steps:
  - group: "React native navigation android tests"
    steps:
      #
      # Build test fixtures
      #
      - label: ":building_construction: :android: Build RN {{matrix.rn_version}} (Old Arch) test fixture"
        key: "build-react-native-navigation-android-fixture-old-arch"
        timeout_in_minutes: 30
        agents:
          queue: macos-12-arm
        env:
          BUILD_ANDROID: "true"
          RN_VERSION: "{{matrix.rn_version}}"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/react-native-navigation/**/reactnative.apk"
        commands:
          - ./bin/generate-react-native-navigation-fixture
        matrix:
          setup:
            rn_version:
              - "0.71"
              - "0.72"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      - label: ':building_construction: :mac: Build RN {{matrix.rn_version}} (Old Arch) test fixture'
        key: "build-react-native-navigation-ios-fixture-old-arch"
        timeout_in_minutes: 30
        agents:
          queue: "macos-12-arm"
        env:
          BUILD_IOS: "true"
          RN_VERSION: "{{matrix.rn_version}}"
          DEVELOPER_DIR: "/Applications/Xcode14.app"
        artifact_paths:
          - "test/react-native/features/fixtures/generated/react-native-navigation/**/reactnative.ipa"
        commands:
          - ./bin/generate-react-native-navigation-fixture
        matrix:
          setup:
            rn_version:
              - "0.71"
              - "0.72"
        retry:
          automatic:
            - exit_status: "*"
              limit: 1

      #
      # End-to-end tests
      #
      - label: ":bitbar: :android: RN {{matrix.rn_version}} (Old Arch) Android {{matrix.android_version}} end-to-end tests"
        depends_on: "build-react-native-navigation-android-fixture-old-arch"
        timeout_in_minutes: 60
        plugins:
          artifacts#v1.9.0:
            download: "test/react-native/features/fixtures/generated/react-native-navigation/old-arch/{{matrix.rn_version}}/reactnative.apk"
            upload: ./test/react-native/maze_output/**/*
          docker-compose#v4.7.0:
            pull: react-native-maze-runner
            run: react-native-maze-runner
            service-ports: true
            command:
              - features/react-native-navigation
              - --app=/app/features/fixtures/generated/react-native-navigation/old-arch/{{matrix.rn_version}}/reactnative.apk
              - --farm=bb
              - --device=ANDROID_{{matrix.android_version}}
              - --a11y-locator
              - --fail-fast
              - --no-tunnel
              - --aws-public-ip
        retry:
          manual:
            permit_on_passed: true
        concurrency: 25
        concurrency_group: "bitbar"
        concurrency_method: eager
        matrix:
          setup:
            android_version:
              - "12"
            rn_version:
              - "0.71"
              - "0.72"
