steps:

  #
  # Test fixtures
  #
  - label: ':android: Build RN {{matrix}} test fixture APK'
    key: "build-react-native-android-fixture"
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    env:
      RN_VERSION: "{{matrix}}"
      BUILD_ANDROID: "true"
    artifact_paths:
      - "build/react-native/**/reactnative.apk"
    commands:
      - ./bin/generate-react-native-fixture
    matrix:
      - "0.72"

  - label: ':mac: Build RN {{matrix}} test fixture ipa'
    key: "build-react-native-ios-fixture"
    timeout_in_minutes: 30
    agents:
      queue: "macos-12-arm"
    env:
      RN_VERSION: "{{matrix}}"
      BUILD_IOS: "true"
      DEVELOPER_DIR: "/Applications/Xcode14.app"
    artifact_paths:
      - "build/react-native/**/output/reactnative.ipa"
    commands:
      - ./bin/generate-react-native-fixture
    matrix:
      - "0.72"

    #
    # End-to-end tests
    #
  - label: ":bitbar: :android: RN {{matrix}} Android 12 end-to-end tests"
    depends_on: "build-react-native-android-fixture"
    timeout_in_minutes: 60
    plugins:
      artifacts#v1.9.0:
        download: "build/react-native/{{matrix}}/reactnative.apk"
        upload: ./test/react-native/maze_output/**/*
      docker-compose#v4.7.0:
        pull: react-native-maze-runner
        run: react-native-maze-runner
        service-ports: true
        command:
          - --app=build/react-native/{{matrix}}/reactnative.apk
          - --farm=bb
          - --device=ANDROID_13
          - --a11y-locator
          - --fail-fast
          - --no-tunnel
          - --aws-public-ip
    env:
      SKIP_NAVIGATION_SCENARIOS: "true"
      HERMES: "true"
    concurrency: 25
    concurrency_group: "bitbar-app"
    concurrency_method: eager
    matrix:
    - "0.72"