# CI test image for unit/lint/type tests
FROM node:18-alpine as browser-feature-builder

RUN apk add --update bash python3 make gcc g++ musl-dev xvfb-run ruby

WORKDIR /app

COPY . .
RUN npm install

# Install packages
WORKDIR /app/test/browser
RUN ruby ./features/support/build-packages.rb

# The maze-runner bitbar browser tests (W3C protocol)
FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner-releases:latest-v7-cli as browser-maze-runner

COPY --from=browser-feature-builder /app/test/browser /app/test/browser/
WORKDIR /app/test/browser

RUN bundle install

ENV SKIP_BUILD_PACKAGES=true
