FROM 855461928731.dkr.ecr.us-west-1.amazonaws.com/maze-runner:tms-click-element-fix-cli

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get install -y nodejs

# Copy repo
WORKDIR /app
COPY . .

# Install packages
RUN npm ci
WORKDIR /app/test/browser

ARG USE_CDN_BUILD
RUN USE_CDN_BUILD=$USE_CDN_BUILD SKIP_FIXTURE_CLEANUP=true ruby ./features/support/build-packages.rb

# Don't rebuild packages during e2e tests
ENV SKIP_BUILD_PACKAGES=true
