FROM node:24-alpine@sha256:01743339035a5c3c11a373cd7c83aeab6ed1457b55da6a69e014a95ac4e4700b as license-finder

RUN apk update && apk add ruby ruby-dev build-base

RUN gem install racc license_finder -v 7.1.0

WORKDIR /scan

CMD npm i && ./bin/license-finder