FROM node:18-alpine@sha256:e0340f26173b41066d68e3fe9bfbdb6571ab3cad0a4272919a52e36f4ae56925 as license-finder

RUN apk update && apk add ruby ruby-dev build-base

RUN gem install license_finder

WORKDIR /scan

CMD npm i && ./bin/license-finder
