name: Publish packages

on:
  push:
    branches: ['next']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - run: npm ci
      - run: npm run build
      - run: npx lerna publish --canary --force-publish --preid alpha.$(git rev-parse --short HEAD) --yes --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
